algoritmo "semnome"
// Função :
// Autor :
// Data : 23/08/2022
// Seção de Declarações 
var
contador,n,soma:inteiro
media:real
qtnd:real
inicio
// Seção de Comandos

para contador de 1 ate 527 faca

se (contador mod 2 = 0) entao
   soma <- soma + contador
   qtnd <- qtnd + 1
fimse

 fimpara
        escreval("o resultado é" , soma)
        escreval("achamos " , qtnd ,"  n° pares")
        media <- soma/qtnd
       escreval("a media é" , media)




fimalgoritmo
