algoritmo "semnome"
// Função :
// Autor :
// Data : 08/03/2022
// Seção de Declarações 
var
nome:caracter
idade:caracter
zap:caracter
inicio
// Seção de Comandos 
escreval ("Digite seu nome:")
leia (nome)
escreval("Digite sua idade")
leia (idade)
escreval("digite seu zap:")
leia (zap)
escreval("bem vindo", nome)
escreval("Qualquer duvida entre em contato com o criador:930857242")

fimalgoritmo
