algoritmo "000000000000"
// Função :
// Autor :gabriel r
// Data : 16/08/2005
// Seção de Declarações 
var
TIME:caracter
inicio
// Seção de Comandos 
escreval("DIGITE NOME DE SEU TIME:")
leia(TIME)
caso "Flamego","Vasco","Botafogo","Fluminense"
escreval ("Eixo RJ")
caso "santos","Corinthians","Palmeiras","São Paulo"
escreval("Eixo SP")
outrocaso
         Escreval("nao esta em nosso registro")




FIMALGORITMO
