algoritmo "calcula media"
// Função :calcular a media de duas notas
// Autor :Gabriel Rodrigues Rolim
// Data : 26/04/2022
// Seção de Declarações 
var
p1,p2:real
media:real
inicio
//DADOS DE ENTRADA
escreval("Entre com um valor para P1")
leia(p1)
escreval("Entre com um valor para p2")
leia(p2)
//FIM DADOS DE ENTRADA
//PROCESSAMENTO
media<- (p1+p2)/2
//FIM DE PROCESSAMENTO
//DADOS DE SAIDA
escreval("a media do aluno é: ",media)
// FIM DOS DADOS DE SAIDA
fimalgoritmo
